// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Products service",
    "version": "1",
    "description": "Swagger API generated by serverless-auto-swagger"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProducts",
        "description": "",
        "operationId": "getProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Succesful response",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          }
        }
      }
    },
    "/product": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.product",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Succesful response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/Body404Type"
            }
          }
        }
      },
      "post": {
        "summary": "addProduct",
        "description": "",
        "operationId": "addProduct.post.product",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddProductBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Succesful response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "AddProductBody": {
      "properties": {
        "count": {
          "title": "AddProductBody.count",
          "type": "number"
        },
        "description": {
          "title": "AddProductBody.description",
          "type": "string"
        },
        "price": {
          "title": "AddProductBody.price",
          "type": "number"
        },
        "title": {
          "title": "AddProductBody.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "AddProductBody",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "Body404Type": {
      "properties": {
        "message": {
          "title": "Body404Type.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "Body404Type",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};